### PR TITLE
Fix/application detail missing

### PR DESCRIPTION
**Pull request by tensulin**
@vktrrdk 

Fixed Dissemetation Details are not shown when submitting application.

https://github.com/deNBI/cloud-portal-webapp/issues/1983

Try to fulfill the following points before the Pull Request is merged:

- [ ] Give a meaningfull description for the PR
- [ ] The PR is reviewed by one of the team members.
- [ ] It must be checked if anything in the Readme must be adjusted (development-, production-, setup).
- [ ] It must be checked if any section in the wiki (https://cloud.denbi.de/wiki/) should be adjusted.
- [ ] If the PR is merged in the master then a release should be be made.
- [ ] The PR is responsive on smaller screens.
- [ ] If the requirements.txt have changed, check if the patches still work
- [ ] If the new code is well commented
- [ ] In case the code is not well commented: An respectice commenting issue with tag "important" is opened.
- [ ] If a squash of commits is required, it has been performed or will be performed at final merge
- [ ] Finally a second team member checks if all requirements met

For releases only:

- [ ] If the review of this PR is approved and the PR is followed by a release then the .env file 
  in the cloud-portal repo should also be updated.

### CODE REVIEW

**Review by eKatchko — APPROVED** [review]

**Review by vktrrdk — COMMENTED** [review]
Does only show one type of information which is allowed

**Comment by tensulin** [comment]
ok i fixed it now, the allowed information was not updated in the dissemination class. I also changed the order of the dissemniation information to match the order in the application form.

**Comment by vktrrdk** [comment]
Still not showing everything in application overview (have send you the screenshots)

**Comment by tensulin** [comment]
i did not check the information in the information overview. The application dissemiation was not correctly initialized, i fixed that. Also i added commas and spaces in the overview so it looks nicer.

**Review by vktrrdk — APPROVED** [review]

**Pull request merged**
